---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

### Technical part, library load etc. 

```{r,echo=TRUE,results='hide', message=FALSE, warning=FALSE}
library(utils)
library(dplyr)
```

### Loading and preprocessing the data


```{r,echo=TRUE,results='hide', message=FALSE, warning=FALSE}
data_source <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
data_dest <- paste(getwd(), "/activity.zip", sep = "")
download.file(data_source, data_dest)
unzip(data_dest)
data_read <- paste(getwd(), "/activity.csv", sep = "")

base_data <- read.csv(data_read, header = TRUE, sep = ",")

```
Lets check if data were loaded properly:

```{r}
head(base_data)
```

### What is mean total number of steps taken per day?

```{r}


```


### What is the average daily activity pattern?



### Imputing missing values



### Are there differences in activity patterns between weekdays and weekends?
